# Generated by Django 3.2.16 on 2022-10-17 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommessage',
            old_name='messagebody',
            new_name='body',
        ),
    ]
