# Generated by Django 3.2.16 on 2022-10-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rename_messagebody_roommessage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-roomupdated', '-roomcreated']},
        ),
    ]
