# Generated by Django 3.2.16 on 2022-10-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_chatroom_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterModelOptions(
            name='roommessage',
            options={'ordering': ['-messageupdated', '-messagecreated']},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
